[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit DRV2605 Library
    adafruit/Adafruit TCA9548A Library
    sparkfun/Sparkfun MAX1704x Fuel Gauge Arduino Library
    earlephilhower/ESP8266Audio