[env:esp32dev]
platform = espressif32@^6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; fix blank serial monitor output on ESP32-S3 boards
monitor_dtr = 0
monitor_rts = 0

; --- N16R8-specific memory config ---
; 16MB Flash = Quad (QIO), 8MB PSRAM = Octal (OPI)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    adafruit/Adafruit VL53L7CX 
    adafruit/Adafruit DRV2605 Library
    esphome/ESP32-audioI2S
    wifwaf/TCA9548A
    sparkfun/Sparkfun MAX1704x Fuel Gauge Arduino Library