[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; --- N16R8-specific memory config ---
; 16MB Flash = Quad (QIO), 8MB PSRAM = Octal (OPI)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    sparkfun/SparkFun VL53L5CX Arduino Library
    adafruit/Adafruit DRV2605 Library
    sparkfun/Sparkfun MAX1704x Fuel Gauge Arduino Library
    https://github.com/schreibfaul1/ESP32-audioI2S.git
    wifwaf/TCA9548A